Remove unnecessary \n in makefile
This pull request removes a *\n* in the makefile function *buildDateTime* causing build errors on Linux.

`buildDateTime.h:4:28: error: stray '\' in program
 #define BUILD_TIME "162841"\n
                            ^`

`In file included from DiscImageCreator.cpp:18:
DiscImageCreator.cpp: In function 'int printSeveralInfo(LPTSTR, size_t)':
buildDateTime.h:4:29: error: expected ')' before 'n'
 #define BUILD_TIME "162841"\n
                             ^`

**Before (buildDateTime.h):**
`#define BUILD_TIME "162533"\n`

**After (buildDateTime.h):**
`#define BUILD_TIME "162617"`